---

- hosts: all

  tasks:
    - name: Start setup website files.
      ansible.builtin.import_role:
        name: files_setup

    - name: Start setup services.
      ansible.builtin.import_role:
        name: services_setup
